# It extends the default conf by adjusting some options.
extends: default

ignore: |
  common/istio/cluster-local-gateway/base/cluster-local-gateway.yaml
  common/istio/istio-crds/base/crd.yaml
  common/istio/istio-install/base/install.yaml

rules:
  document-start:
    present: false
  document-end:
    present: false
  indentation:
    spaces: 2
    indent-sequences: consistent
    check-multi-line-strings: false
  line-length:
    max: 400
  truthy:
    allowed-values: ["on", "off", "true", "false"]
  empty-lines:
    level: warning
  comments:
    min-spaces-from-content: 1  # More lenient than default 2
  comments-indentation: disable  # Prettier handles this
